--- MEDICINES ---
ALTER TABLE Medicines ADD CONSTRAINT FK_MEDICINES_MEDINV FOREIGN KEY (idMedicationInventory) REFERENCES MedicationInventory(idMedicationInventory) ON DELETE SET NULL;
ALTER TABLE Medicines ADD CONSTRAINT FK_MEDICINES_MANAGEPLAN FOREIGN KEY (idManagementPlan) REFERENCES ManagementPlan(idManagementPlan) ON DELETE SET NULL;

--- EXAMS ---
ALTER TABLE Exams ADD CONSTRAINT FK_EXAMS_MANAGEPLAN FOREIGN KEY (idManagementPlan) REFERENCES ManagementPlan(idManagementPlan) ON DELETE SET NULL;

--- MEDICINE COMPONENTS ---
ALTER TABLE MedicationComponents ADD CONSTRAINT FK_MEDICATIONC_MEDICINE FOREIGN KEY (idMedicines) REFERENCES Medicines(idMedicines) ON DELETE SET NULL;

--- PROCEDURES ---
ALTER TABLE Procedures ADD CONSTRAINT FK_PROCEDURE_MANAGEPLAN FOREIGN KEY (idManagementPlan) REFERENCES ManagementPlan(idManagementPlan) ON DELETE SET NULL;

--- DISEASES ---
ALTER TABLE Disease ADD CONSTRAINT FK_DISEASE_BACKGROUND FOREIGN KEY (idBackground) REFERENCES Background(idBackground) ON DELETE SET NULL;