--- X DISPARADORES ---
DROP TRIGGER "BD2172577"."INSERT_MED_TYPE"; 
DROP TRIGGER "BD2172577"."INSERT_MED_INVENTORY"; 
DROP TRIGGER "BD2172577"."INSERT_SUPPLY_INVENTORY"; 
DROP TRIGGER "BD2172577"."INSERT_CITY"; 
DROP TRIGGER "BD2172577"."INSERT_MU"; 
DROP TRIGGER "BD2172577"."INSERT_PERSONA"; 

--- DISPARADORES ---
--- MEDICATION TYPE---
CREATE OR REPLACE TRIGGER INSERT_MED_TYPE
BEFORE INSERT ON MEDICATIONTYPE 
FOR EACH ROW
BEGIN
  SELECT "BD2172577"."ID_MEDICATION_TYPE".NEXTVAL INTO :NEW.idMedicationType FROM DUAL;
END;

/

--- MEDICATION INVENTORY---
CREATE OR REPLACE TRIGGER INSERT_MED_INVENTORY
BEFORE INSERT ON MEDICATIONINVENTORY 
FOR EACH ROW
BEGIN
  SELECT "BD2172577"."ID_MEDICATION_INVENTORY".NEXTVAL INTO :NEW.idMedicationInventory FROM DUAL;
END;

/

--- SUPPLIES INVENTORY ---
CREATE OR REPLACE TRIGGER INSERT_SUPPLY_INVENTORY
BEFORE INSERT ON SuppliesInventory 
FOR EACH ROW
BEGIN
  SELECT "BD2172577"."ID_SUPPLY_INVENTORY".NEXTVAL INTO :NEW.idSuppliesInventory FROM DUAL;
END;

/ 

--- CITY ---
CREATE OR REPLACE TRIGGER INSERT_CITY
BEFORE INSERT ON CITY 
FOR EACH ROW
BEGIN
  SELECT "BD2172577"."ID_CITY".NEXTVAL INTO :NEW.idCity FROM DUAL;
END;

/ 

--- MILITARY UNIT ---
CREATE OR REPLACE TRIGGER INSERT_MU
BEFORE INSERT ON MilitaryUnit 
FOR EACH ROW
BEGIN
  SELECT "BD2172577"."ID_MU".NEXTVAL INTO :NEW.idMilitaryUnit FROM DUAL;
END;

/ 

--- HOSPITAL ---
CREATE OR REPLACE TRIGGER INSERT_HOSPITAL
BEFORE INSERT ON HOSPITAL 
FOR EACH ROW
BEGIN
  SELECT "BD2172577"."ID_HOSPITAL".NEXTVAL INTO :NEW.idHospital FROM DUAL;
END;

/ 

--- PERSON ---
CREATE OR REPLACE TRIGGER INSERT_PERSONA
BEFORE INSERT ON PERSON
FOR EACH ROW
BEGIN
    :new.registerDate := sysdate;
END;

/