--- X DISPARADORES ---
DROP TRIGGER INSERT_MED_TYPE; 
DROP TRIGGER INSERT_MED_INVENTORY; 
DROP TRIGGER INSERT_SUPPLY_INVENTORY; 
DROP TRIGGER INSERT_CITY; 
DROP TRIGGER INSERT_MU; 
DROP TRIGGER INSERT_PERSONA; 
DROP TRIGGER INSERT_PATIENT; 
DROP TRIGGER INSERT_CLINICAL_HISTORY; 
DROP TRIGGER INSERT_SPECIALTY; 
DROP TRIGGER INSERT_BACKGROUND; 
DROP TRIGGER INSERT_LABORATORY; 


--- DISPARADORES ---
--- MEDICATION TYPE---
CREATE OR REPLACE TRIGGER INSERT_MED_TYPE
BEFORE INSERT ON MEDICATIONTYPE 
FOR EACH ROW
BEGIN
  SELECT ID_MEDICATION_TYPE.NEXTVAL INTO :NEW.idMedicationType FROM DUAL;
END;

/

--- MEDICATION INVENTORY---
CREATE OR REPLACE TRIGGER INSERT_MED_INVENTORY
BEFORE INSERT ON MEDICATIONINVENTORY 
FOR EACH ROW
BEGIN
  SELECT ID_MEDICATION_INVENTORY.NEXTVAL INTO :NEW.idMedicationInventory FROM DUAL;
END;

/

--- SUPPLIES INVENTORY ---
CREATE OR REPLACE TRIGGER INSERT_SUPPLY_INVENTORY
BEFORE INSERT ON SuppliesInventory 
FOR EACH ROW
BEGIN
  SELECT ID_SUPPLY_INVENTORY.NEXTVAL INTO :NEW.idSuppliesInventory FROM DUAL;
END;

/ 

--- CITY ---
CREATE OR REPLACE TRIGGER INSERT_CITY
BEFORE INSERT ON CITY 
FOR EACH ROW
BEGIN
  SELECT ID_CITY.NEXTVAL INTO :NEW.idCity FROM DUAL;
END;

/ 

--- MILITARY UNIT ---
CREATE OR REPLACE TRIGGER INSERT_MU
BEFORE INSERT ON MilitaryUnit 
FOR EACH ROW
BEGIN
  SELECT ID_MU.NEXTVAL INTO :NEW.idMilitaryUnit FROM DUAL;
END;

/ 

--- HOSPITAL ---
CREATE OR REPLACE TRIGGER INSERT_HOSPITAL
BEFORE INSERT ON HOSPITAL 
FOR EACH ROW
BEGIN
  SELECT ID_HOSPITAL.NEXTVAL INTO :NEW.idHospital FROM DUAL;
END;

/ 

--- PERSON ---
CREATE OR REPLACE TRIGGER INSERT_PERSONA
BEFORE INSERT ON PERSON
FOR EACH ROW
BEGIN
    :new.registerDate := sysdate;
END;

/

--- PENDIENTE DE PRUEBAS

--- PATIENT ---
CREATE OR REPLACE TRIGGER INSERT_PATIENT
BEFORE INSERT ON PATIENT 
FOR EACH ROW
BEGIN
  SELECT ID_DISAN_PATIENT.NEXTVAL INTO :NEW.disanId FROM DUAL;
END;

/

--- CLINICAL HISTORY ---
CREATE OR REPLACE TRIGGER INSERT_CLINICAL_HISTORY
BEFORE INSERT ON CLINICALHISTORY 
FOR EACH ROW
BEGIN
  SELECT ID_CLINICAL_HISTORY.NEXTVAL INTO :NEW.idClinicalHistory FROM DUAL;
END;

/

--- SPECIALTY ---
CREATE OR REPLACE TRIGGER INSERT_SPECIALTY
BEFORE INSERT ON SPECIALTY 
FOR EACH ROW
BEGIN
  SELECT ID_SPECIALTY.NEXTVAL INTO :NEW.idSpeciality FROM DUAL;
END;

/

--- BACKGROUND ---
CREATE OR REPLACE TRIGGER INSERT_BACKGROUND
BEFORE INSERT ON BACKGROUND 
FOR EACH ROW
BEGIN
  SELECT ID_BACKGROUND.NEXTVAL INTO :NEW.idBackground FROM DUAL;
END;

/

--- LABORATORY ---
CREATE OR REPLACE TRIGGER INSERT_LABORATORY
BEFORE INSERT ON LABORATORY 
FOR EACH ROW
BEGIN
  SELECT ID_LABORATORY.NEXTVAL INTO :NEW.idLaboratory FROM DUAL;
END;

/