--- MEDICATION TYPE ---
SELECT * FROM MEDICATIONTYPE ORDER BY idmedicationtype;

--- MEDICATION INVENTORY ---
SELECT * FROM MEDICATIONINVENTORY ORDER BY idMedicationInventory;

--- SUPPLIES INVENTORY ---
SELECT * FROM SuppliesInventory ORDER BY idSuppliesInventory;

--- CITY ---
SELECT * FROM City ORDER BY idCity;

--- MILITARY UNIT ---
SELECT * FROM MilitaryUnit ORDER BY idMilitaryUnit;