-- DOCTOR
-- SPECIFIC EXAM
SELECT PA_DOCTOR.READ_SPEC_EXAMS(1) FROM DUAL;

-- EXAM LAB
SELECT PA_DOCTOR.READ_EXAM_LAB(1) FROM DUAL;

-- READ ALL EXAMS
SELECT PA_DOCTOR.READ_ALL_EXAMS FROM DUAL;

-- UPDATE EXAM LAB
EXECUTE PA_DOCTOR.UPDATE_EXAM_LAB(1, 1);

-- ADD EXAM LAB
EXECUTE PA_DOCTOR.ADD_EXAM_LAB(5,  2);

-- ADD EXAM
EXECUTE PA_DOCTOR.ADD_EXAM('EXAMEN DE PRUEBA');

-- READ MED TYPES
SELECT PA_DOCTOR.READ_MED_TYPES FROM DUAL;

-- UPDATE MEDICATION INVENTORY
EXECUTE PA_DOCTOR.UPDATE_MEDICATION_INVENTORY(444, 888);

-- READ MEDICATION INVENTORY
SELECT PA_DOCTOR.READ_MEDICATION_INVENTORY FROM DUAL;

-- READ MED COMPONENTS
SELECT PA_DOCTOR.READ_MED_COMPONENTS FROM DUAL;

-- READ ALL MEDICINES
SELECT PA_DOCTOR.READ_ALL_MEDICINES FROM DUAL;

-- READ SUPPLY
SELECT PA_DOCTOR.READ_SUPPLY FROM DUAL;

-- UPDATE SUPPLY
EXECUTE PA_DOCTOR.UPDATE_SUPPLY(11, 55,3);

-- READ LABORATORY
SELECT PA_DOCTOR.READ_LABORATORY FROM DUAL;

-- READ CITY
SELECT PA_DOCTOR.READ_CITY FROM DUAL;

-- READ APPOINTMENTS
SELECT PA_DOCTOR.READ_APPOINTMENTS FROM DUAL;

-- ADD APPOINTMENT
EXECUTE PA_DOCTOR.ADD_APPOINTMENT(4, 'CITA DE PRUEBA', TO_TIMESTAMP('07/09/2021 14:00', 'MM/DD/YYYY hh24:mi'), 1);

-- ADD APPOINTMENT DOCTOR
EXECUTE PA_DOCTOR.ADD_APPOINTMENT_DOCTOR('CC', 1773190621, 2);

-- ADD DIAGNOSIS
EXECUTE PA_DOCTOR.ADD_DIAGNOSIS(2, 'DIAGNÓSTICO DE PRUEBA');

-- READ MANAGEMENT PLAN
SELECT PA_DOCTOR.READ_MANAGEMENT_PLAN FROM DUAL;

-- ADD MANAGEMENT PLAN
EXECUTE PA_DOCTOR.ADD_MANAGEMENT_PLAN('NUEVO PLAN DE MANEJO');

-- ADD MANAGEMENT PLAN TO APPOINTMENT
EXECUTE PA_DOCTOR.ADD_MANAGE_TO_APP(11, 2);

-- READ ALL HOSPITALS
SELECT PA_DOCTOR.READ_HOSPITAL FROM DUAL;

-- UPDATE HOSPITAL
EXECUTE PA_DOCTOR.UPDATE_HOSPITAL(10, 'HOSPITAL MODIFICADO', 55, 55, 30, 'NUEVA DIRECCIÓN');

-- READ SPECIFIC NURSE
SELECT PA_DOCTOR.READ_SPECIFIC_NURSE('CC', 7933982639) FROM DUAL;

-- READ ALL NURSES
SELECT PA_DOCTOR.READ_NURSE FROM DUAL;

-- READ SPECIFIC PATIENT
SELECT PA_DOCTOR.READ_SPECIFIC_PATIENT('TI', 1948559565) FROM DUAL;

-- READ PATIENT BACKGROUND PROCEDURE
SELECT PA_DOCTOR.READ_PATIENT_BACK_PROC('TI', 1948559565) FROM DUAL;

-- READ PATIENT BACKGROUND DISEASE
SELECT PA_DOCTOR.READ_PATIENT_BACK_DIS('TI', 1948559565) FROM DUAL;

-- ADD CLINICAL HISTORY
EXECUTE PA_DOCTOR.ADD_CLINICAL_HISTORY('TI', 1948559565);

-- READ CLINICAL HISTORY
SELECT PA_DOCTOR.READ_CLINICAL_HISTORY('TI', 1948559565) FROM DUAL;

-- ADD BACKGROUND
EXECUTE PA_DOCTOR.ADD_BACKGROUND(1);

-- READ PATIENT BACKGROUNDS
SELECT PA_DOCTOR.READ_PATIENT_BACKGROUNDS(1) FROM DUAL;

-- READ DISEASES
SELECT PA_DOCTOR.READ_DISEASES FROM DUAL;

-- READ PROCEDURES
SELECT PA_DOCTOR.READ_PROCEDURES FROM DUAL;

-- READ SPECIFIC DOCTOR PROCEDURES
SELECT PA_DOCTOR.READ_DOCTOR_PROCEDURES('CC', 1773190621) FROM DUAL;

-- READ SPECIFIC NURSE PROCEDURES
SELECT PA_DOCTOR.READ_NURSE_PROCEDURES('CC', 7933982639) FROM DUAL;

-- ADD PROCEDURE DOCTOR
EXECUTE PA_DOCTOR.ADD_PROCEDURE_DOCTOR('CC', 2878196529, 1);

-- ADD PROCEDURE NURSE
EXECUTE PA_DOCTOR.ADD_PROCEDURE_NURSE('CC', 4252609306, 1);

-- FINISH APPOINTMENT
EXECUTE PA_DOCTOR.FINISH_APPOINTMENT(1);

-- FINISH PROCEDURE
EXECUTE PA_DOCTOR.FINISH_PROCEDURE(1);

