-- PROCEDURES
CREATE INDEX IDX_PROCEDURES ON PROCEDURES (name);

-- HOSPITALS
CREATE INDEX IDX_HOSPITALS ON HOSPITAL (name);

-- MEDICINES
CREATE INDEX IDX_MEDICINES ON MEDICINES (commercialName);

-- LABORATORIES
CREATE INDEX IDX_LABORATORY ON LABORATORY (name);
