-- CLINICAL HISTORY
CREATE OR REPLACE VIEW V_CLINICAL_HISTORY AS
    SELECT 
    ClinicalHistory.documentType AS PATIENT_DOC_TYPE,
    ClinicalHistory.documentNumber AS PATIENT_DOC_NUMBER,
    PROCEDURES.name AS PROCEDURE,
    DISEASE.name AS DISEASE,
    APPOINTMENT.appointmentMotive AS APP_MOTIVE,
    APPOINTMENT.diagnosis AS APP_DIAGNOSIS,
    APPOINTMENT.dateAppointment AS APP_DATE
    FROM
    ClinicalHistory
    JOIN BACKGROUND ON ClinicalHistory.idClinicalHistory = BACKGROUND.idClinicalHistory
    JOIN DISEASE ON BACKGROUND.idBackground = DISEASE.idBackground
    JOIN PROCEDURES ON ClinicalHistory.idClinicalHistory = PROCEDURES.idClinicalHistory
    JOIN APPOINTMENT ON ClinicalHistory.idClinicalHistory = APPOINTMENT.idClinicalHistory
    ORDER BY ClinicalHistory.documentType, ClinicalHistory.documentNumber;
    

-- HOSPITAL
CREATE OR REPLACE VIEW V_HOSPITAL AS
    SELECT
    HOSPITAL.name AS NAME,
    HOSPITAL.address AS ADDRESS,
    HOSPITAL.bedNumber AS BED_NUMBER,
    HOSPITAL.UCINumber AS UCI_NUMBER,
    CITY.name AS CITY,
    MILITARYUNIT.name AS BATTALION
    FROM HOSPITAL
    JOIN CITY ON HOSPITAL.idCity = CITY.idCity
    JOIN BATTALION ON HOSPITAL.idBattalion = BATTALION.idBattalion
    JOIN MILITARYUNIT ON HOSPITAL.idBattalion = MILITARYUNIT.idMilitaryUnit
    ORDER BY idHospital;
    

-- MEDICINES
CREATE OR REPLACE VIEW V_MEDICINES AS
    SELECT
    MEDICINES.commercialName AS COMMERCIAL_NAME,
    MEDICINES.presentation AS PRESENTATION,
    MEDICINES.producer AS PRODUCER
    FROM MEDICINES
    ORDER BY idMedicines;


-- SUPPLIES
CREATE OR REPLACE VIEW V_SUPPLIES AS
    SELECT
    SUPPLY.idSupply AS ID,
    SUPPLY.name AS NAME,
    SUPPLY.amount AS AMOUNT,
    SUPPLY.idSuppliesInventory AS INVENTORY
    FROM SUPPLY
    ORDER BY idSupply;


-- HOSPITAL
CREATE OR REPLACE VIEW V_LABORATORY AS
    SELECT
    LABORATORY.name AS NAME,
    LABORATORY.address AS ADDRESS,
    CITY.name AS CITY,
    MILITARYUNIT.name AS BATTALION
    FROM LABORATORY
    JOIN CITY ON LABORATORY.idCity = CITY.idCity
    JOIN BATTALION ON LABORATORY.idBattalion = BATTALION.idBattalion
    JOIN MILITARYUNIT ON LABORATORY.idBattalion = MILITARYUNIT.idMilitaryUnit
    ORDER BY idLaboratory;
    
-- APPOINTMENT
CREATE OR REPLACE VIEW V_APPOINTMENT AS
    SELECT
    APPOINTMENT.idAppointment AS ID,
    APPOINTMENT.appointmentMotive AS MOTIVE,
    APPOINTMENT.diagnosis AS DIAGNOSIS,
    APPOINTMENT.dateAppointment AS APP_DATE,
    HOSPITAL.name AS HOSPITAL,
    HOSPITAL.address AS ADDRESS,
    CITY.name AS CITY,
    MILITARYUNIT.name AS BATTALION
    FROM APPOINTMENT    
    JOIN HOSPITAL ON APPOINTMENT.idHospital = HOSPITAL.idHospital
    JOIN CITY ON HOSPITAL.idCity = CITY.idCity
    JOIN MILITARYUNIT ON HOSPITAL.idBattalion = MILITARYUNIT.idMilitaryUnit
    ORDER BY idAppointment;

-- BACKGROUNDS
CREATE OR REPLACE VIEW V_BACKGROUND AS
    SELECT
    Disease.name AS DISEASE_NAME,
    Disease.description AS DISEASE_DESCRIPTION,
    Procedures.name AS PROCEDURE,
    Procedures.dateProcedure AS PROCEDURE_DATE
    FROM BACKGROUND    
    JOIN DISEASE ON BACKGROUND.idBackground = DISEASE.idBackground
    JOIN PROCEDURES ON BACKGROUND.idBackground = PROCEDURES.idBackground
    ORDER BY BACKGROUND.idBackground;


 -- MILITARY UNIT   
 CREATE OR REPLACE VIEW V_MILITARY_UNIT AS
    SELECT 
    MilitaryUnit.idMilitaryUnit AS ID,
    MilitaryUnit.name AS NAME,
    CITY.name AS CITY,
    MilitaryUnit.fullLocation AS LOCATION
    FROM MILITARYUNIT    
    JOIN CITY ON MILITARYUNIT.city = CITY.idCity
    ORDER BY idMilitaryUnit;

 -- DIVISION 
 CREATE OR REPLACE VIEW V_DIVISION AS
    SELECT 
    DIVISION.idDivision AS ID,
    MilitaryUnit.name AS NAME,
    DIVISION.commander AS COMMANDER,
    CITY.name AS CITY,
    MilitaryUnit.fullLocation AS LOCATION,
    DIVISION.militaryForce AS MILITARY_FORCE
    FROM DIVISION
    JOIN MILITARYUNIT ON DIVISION.idDivision = MILITARYUNIT.idMilitaryUnit
    JOIN CITY ON MILITARYUNIT.city = CITY.idCity
    ORDER BY idDivision;

-- BRIGADE
 CREATE OR REPLACE VIEW V_BRIGADE AS
    SELECT 
    BRIGADE.idBrigade AS ID,
    M1.name AS NAME,
    BRIGADE.commander AS COMMANDER,
    MilitaryUnit.name AS DIVISION,
    CITY.name AS CITY,
    MilitaryUnit.fullLocation AS LOCATION,
    BRIGADE.militaryForce AS MILITARY_FORCE
    FROM BRIGADE
    JOIN MILITARYUNIT M1 ON BRIGADE.idBrigade = M1.idMilitaryUnit
    JOIN MILITARYUNIT ON BRIGADE.idDivision = MILITARYUNIT.idMilitaryUnit
    JOIN CITY ON MILITARYUNIT.city = CITY.idCity
    ORDER BY idBrigade;

