-- SUPPLY
EXECUTE PKG_SUPPLY.ADD_SUPPLY('TEST2', 1000, 15);
EXECUTE PKG_SUPPLY.ADD_SUPPLY('TEST2', 14578965824, 10);
EXECUTE PKG_SUPPLY.UPDATE_SUPPLY(16, 'TEST UPDATED 2', 11, 15);

-- SUPPLIES INVENTORY
EXECUTE PKG_SUPPLIES_INVENTORY.UPDATE_SUPPLIES_INVENTORY(1520, 3);

-- MILITARY UNIT
EXECUTE PKG_MILITARY_UNIT.ADD_MILITARY_UNIT('UNIDAD DE PRUEBA', 5, NULL);
EXECUTE PKG_MILITARY_UNIT.ADD_MILITARY_UNIT('UNIDAD DE PRUEBA', 5, NULL);
EXECUTE PKG_MILITARY_UNIT.ADD_MILITARY_UNIT(NULL, 5, NULL);

-- DIVISION
EXECUTE PKG_MILITARY_UNIT.ADD_DIVISION(NULL, NULL, NULL, NULL, 'rmadAAA');
EXECUTE PKG_MILITARY_UNIT.UPDATE_DIVISION('asdaghfgjf','comandante de prueba', 'Fuerza AAerea');

-- BRIGADE
EXECUTE PKG_MILITARY_UNIT.ADD_BRIGADE('NUEVA BRIGADA', NULL, NULL, 'HOLIWI', 'TEST 3', 'Armada');
EXECUTE PKG_MILITARY_UNIT.UPDATE_BRIGADE('Brigada 11', NULL, 'TEST 3', NULL);

-- BATTALION
EXECUTE PKG_MILITARY_UNIT.ADD_BATTALION(NULL, 'Armenia', NULL, 'EL COMANDANTE', 'Brigada 11', 'Armadaa');
EXECUTE PKG_MILITARY_UNIT.UPDATE_BATTALION('NUEVA BATALLÓN','test2', 'Brigada 27','Fuerza Aerea');

-- LABORATORY
EXECUTE PKG_LABORATORY.ADD_LABORATORY('Nuevo Laboratorio', NULL, 'Batallón 10', NULL);
EXECUTE PKG_LABORATORY.UPDATE_LABORATORY('Nuevo Laboratorio','Batallón 199', NULL);

-- CITY
EXECUTE PKG_CITY.ADD_CITY(NULL, 'Cundinamarca');
EXECUTE PKG_CITY.UPDATE_CITY(33, NULL, NULL);

-- MEDICATION INVENTORY
EXECUTE PKG_MEDICATION_INVENTORY.UPDATE_MEDICATION_INVENTORY(1452, 13);

-- HOSPITAL
EXECUTE PKG_HOSPITAL.ADD_HOSPITAL(NULL, 10, NULL, 'Batallón 2', 'Yopal', 'Dirección 345');
EXECUTE PKG_HOSPITAL.UPDATE_HOSPITAL('Nuevo hospital', NULL, 111, 'Batallón 2', 'Dirección 147');

-- PERSON
EXECUTE PKG_PERSON.ADD_PERSON(NULL, '1235478965', 'PRUEBA', 'UNITARIA', 'M', TO_DATE('01/26/1979', 'MM/DD/YYYY'), 'laprueba@mail.com');
--SELECT PKG_PERSON.READ_PERSON FROM DUAL;
EXECUTE PKG_PERSON.UPDATE_PERSON('CC', '1235478965', 'F', 'lapruebaeditada@mail.com');

-- DOCTOR
EXECUTE PKG_PERSON.ADD_DOCTOR('CC', '1236547859', NULL, 'DE PRUEBA', 'M', TO_DATE('06/26/1980', 'MM/DD/YYYY'), 'doctor1@mail.com', 'Armada', 'Dermatologia');
EXECUTE PKG_PERSON.UPDATE_DOCTOR('CC', NULL, 'I', 'Ejercito', 'Neurocirugia');

-- NURSE
EXECUTE PKG_PERSON.ADD_NURSE('CC', NULL, 'ENFERMERO', 'DE PRUEBA', 'M', TO_DATE('06/26/1980', 'MM/DD/YYYY'), 'enfermero1@mail.com', 'Armada', 'Dermatologia');
--SELECT PKG_PERSON.READ_NURSE FROM DUAL;
EXECUTE PKG_PERSON.UPDATE_NURSE('CC', '1458758965', 'F', 'Ejercito', 'Neurocirugia');
