-- SUPPLY
EXECUTE PKG_SUPPLY.ADD_SUPPLY('TEST2', 1000, 15);
EXECUTE PKG_SUPPLY.ADD_SUPPLY('TEST2', 14578965824, 10);
EXECUTE PKG_SUPPLY.UPDATE_SUPPLY(16, 'TEST UPDATED 2', 11, 15);

-- SUPPLIES INVENTORY
EXECUTE PKG_SUPPLIES_INVENTORY.UPDATE_SUPPLIES_INVENTORY(1520, 3);

-- MILITARY UNIT
EXECUTE PKG_MILITARY_UNIT.ADD_MILITARY_UNIT('UNIDAD DE PRUEBA', 5, NULL);
EXECUTE PKG_MILITARY_UNIT.ADD_MILITARY_UNIT('UNIDAD DE PRUEBA', 5, NULL);
EXECUTE PKG_MILITARY_UNIT.ADD_MILITARY_UNIT(NULL, 5, NULL);

-- DIVISION
EXECUTE PKG_MILITARY_UNIT.ADD_DIVISION(NULL, NULL, NULL, NULL, 'rmadAAA');
EXECUTE PKG_MILITARY_UNIT.UPDATE_DIVISION('asdaghfgjf','comandante de prueba', 'Fuerza AAerea');

-- BRIGADE
EXECUTE PKG_MILITARY_UNIT.ADD_BRIGADE('NUEVA BRIGADA', NULL, NULL, 'HOLIWI', 'TEST 3', 'Armada');
EXECUTE PKG_MILITARY_UNIT.UPDATE_BRIGADE('Brigada 11', NULL, 'TEST 3', NULL);
