-- SUPPLIES INVENTORY
EXECUTE PKG_SUPPLIES_INVENTORY.ADD_SUPPLIES_INVENTORY(NULL);
EXECUTE PKG_SUPPLIES_INVENTORY.ADD_SUPPLIES_INVENTORY(NULL);
EXECUTE PKG_SUPPLIES_INVENTORY.ADD_SUPPLIES_INVENTORY(NULL);
EXECUTE PKG_SUPPLIES_INVENTORY.ADD_SUPPLIES_INVENTORY(NULL);
EXECUTE PKG_SUPPLIES_INVENTORY.ADD_SUPPLIES_INVENTORY(NULL);
EXECUTE PKG_SUPPLIES_INVENTORY.ADD_SUPPLIES_INVENTORY(NULL);
EXECUTE PKG_SUPPLIES_INVENTORY.ADD_SUPPLIES_INVENTORY(NULL);
EXECUTE PKG_SUPPLIES_INVENTORY.ADD_SUPPLIES_INVENTORY(NULL);
EXECUTE PKG_SUPPLIES_INVENTORY.ADD_SUPPLIES_INVENTORY(NULL);
EXECUTE PKG_SUPPLIES_INVENTORY.ADD_SUPPLIES_INVENTORY(NULL);
EXECUTE PKG_SUPPLIES_INVENTORY.ADD_SUPPLIES_INVENTORY(NULL);
EXECUTE PKG_SUPPLIES_INVENTORY.ADD_SUPPLIES_INVENTORY(NULL);

EXECUTE PKG_SUPPLIES_INVENTORY.UPDATE_SUPPLIES_INVENTORY(5, 258);

--SELECT PKG_SUPPLIES_INVENTORY.READ_SUPPLIES_INVENTORY FROM DUAL;


-- SUPPLY
EXECUTE PKG_SUPPLY.ADD_SUPPLY('Supply 1', 1, 1);
EXECUTE PKG_SUPPLY.ADD_SUPPLY('Supply 2', 12, 1);
EXECUTE PKG_SUPPLY.ADD_SUPPLY('Supply 3', 1000, 5);
EXECUTE PKG_SUPPLY.ADD_SUPPLY('Supply 4', 12345, 7);
EXECUTE PKG_SUPPLY.ADD_SUPPLY('Supply 5', 444, 2);
EXECUTE PKG_SUPPLY.ADD_SUPPLY('Supply 6', 2, 1);
EXECUTE PKG_SUPPLY.ADD_SUPPLY('Supply 7', 10900, 4);
EXECUTE PKG_SUPPLY.ADD_SUPPLY('Supply 8', 32, 8);
EXECUTE PKG_SUPPLY.ADD_SUPPLY('Supply 9', 1, 2);
EXECUTE PKG_SUPPLY.ADD_SUPPLY('Supply 10', 50, 3);
EXECUTE PKG_SUPPLY.ADD_SUPPLY('Supply 11', 33, 4);

EXECUTE PKG_SUPPLY.ADD_SUPPLY('TEST', 150, 5);
EXECUTE PKG_SUPPLY.UPDATE_SUPPLY(12, 555, 5);

--SELECT PKG_SUPPLY.READ_SUPPLY FROM DUAL;
--SELECT PKG_SUPPLY.READ_SPEC_SUPPLY('TEST') FROM DUAL;


-- CITY
EXECUTE PKG_CITY.ADD_CITY('Leticia', 'Amazonas'); 
EXECUTE PKG_CITY.ADD_CITY('Medellin', 'Antioquia'); 
EXECUTE PKG_CITY.ADD_CITY('Arauca', 'Arauca'); 
EXECUTE PKG_CITY.ADD_CITY('Barranquilla', 'Atlantico'); 
EXECUTE PKG_CITY.ADD_CITY('Bogota', 'Cundinamarca'); 
EXECUTE PKG_CITY.ADD_CITY('Cartagena', 'Bolivar'); 
EXECUTE PKG_CITY.ADD_CITY('Tunja', 'Boyaca'); 
EXECUTE PKG_CITY.ADD_CITY('Manizales', 'Caldas'); 
EXECUTE PKG_CITY.ADD_CITY('Florencia', 'Caqueta'); 
EXECUTE PKG_CITY.ADD_CITY('Yopal', 'Casanare'); 
EXECUTE PKG_CITY.ADD_CITY('Popayan', 'Cauca'); 
EXECUTE PKG_CITY.ADD_CITY('Valledupar', 'Cesar'); 
EXECUTE PKG_CITY.ADD_CITY('Quibdo', 'Choco'); 
EXECUTE PKG_CITY.ADD_CITY('Monteria', 'Cordoba'); 
EXECUTE PKG_CITY.ADD_CITY('Inirida', 'Guainia'); 
EXECUTE PKG_CITY.ADD_CITY('San Jose del Guaviare', 'Guaviare'); 
EXECUTE PKG_CITY.ADD_CITY('Neiva', 'Huila'); 
EXECUTE PKG_CITY.ADD_CITY('Rioacha', 'La Guajira'); 
EXECUTE PKG_CITY.ADD_CITY('Santa Marta', 'Magdalena'); 
EXECUTE PKG_CITY.ADD_CITY('Villavicencio', 'Meta'); 
EXECUTE PKG_CITY.ADD_CITY('Pasto', 'Nariño'); 
EXECUTE PKG_CITY.ADD_CITY('Cucuta', 'Norte de Santander'); 
EXECUTE PKG_CITY.ADD_CITY('Mocoa', 'Putumayo'); 
EXECUTE PKG_CITY.ADD_CITY('Armenia', 'Quindio'); 
EXECUTE PKG_CITY.ADD_CITY('Pereira', 'Risaralda'); 
EXECUTE PKG_CITY.ADD_CITY('San Andres', 'San Andres y Providencia'); 
EXECUTE PKG_CITY.ADD_CITY('Bucaramanga', 'Santander'); 
EXECUTE PKG_CITY.ADD_CITY('Sincelejo', 'Sucre'); 
EXECUTE PKG_CITY.ADD_CITY('Ibague', 'Tolima'); 
EXECUTE PKG_CITY.ADD_CITY('Cali', 'Valle del Cauca'); 
EXECUTE PKG_CITY.ADD_CITY('Mitu', 'Vaupes'); 
EXECUTE PKG_CITY.ADD_CITY('Puerto Carreño', 'Vichada');



EXECUTE PKG_CITY.ADD_CITY('CIUDAD TEST', 'DEPARTAMENTO TEST');

EXECUTE PKG_CITY.UPDATE_CITY(33, 'Nuevo ciudad editada','Nariño');

--SELECT PKG_CITY.READ_CITY FROM DUAL;





-- MILITARY UNIT
EXECUTE PKG_MILITARY_UNIT.ADD_MILITARY_UNIT('DIVISIÓN 1', 'Medellin', NULL);

EXECUTE PKG_MILITARY_UNIT.UPDATE_MILITARY_UNIT(3, 'zzz22', 'Leticia', 'CALLE 456');

--SELECT PKG_MILITARY_UNIT.READ_MILITARY_UNIT FROM DUAL;

-- DIVISION
EXECUTE PKG_MILITARY_UNIT.ADD_DIVISION('NUEVA DIVISIÓN2', 'Medellin', NULL, 'PEPE EL POLLO2', 'Armada');
--SELECT PKG_MILITARY_UNIT.READ_DIVISION FROM DUAL;
EXECUTE PKG_MILITARY_UNIT.UPDATE_DIVISION('NUEVA DIVISIÓN2','comandante de prueba', 'Fuerza Aerea');

-- BRIGADE
EXECUTE PKG_MILITARY_UNIT.ADD_BRIGADE('NUEVA BRIGADA', 'Cali', NULL, 'HOLIWI', 'División 11', 'Armada');
--SELECT PKG_MILITARY_UNIT.READ_BRIGADE FROM DUAL;
EXECUTE PKG_MILITARY_UNIT.UPDATE_BRIGADE('Brigada 11','comandante de prueba', 'División 11','Fuerza Aerea');

-- BATTALION
EXECUTE PKG_MILITARY_UNIT.ADD_BATTALION('NUEVA BATALLÓN', 'Armenia', NULL, 'EL COMANDANTE', 'Brigada 11', 'Armada');
--SELECT PKG_MILITARY_UNIT.READ_BATTALION FROM DUAL;
EXECUTE PKG_MILITARY_UNIT.UPDATE_BATTALION('NUEVA BATALLÓN','test2', 'Brigada 9','Fuerza Aerea');

-- LABORATORY
EXECUTE PKG_LABORATORY.ADD_LABORATORY('Nuevo Laboratorio', 'Armenia', 'Batallón 10', 'Calle 123 #45 - 56');
--SELECT PKG_LABORATORY.READ_LABORATORY FROM DUAL;
EXECUTE PKG_LABORATORY.UPDATE_LABORATORY('Nuevo Laboratorio','Batallón 1', 'Nueva dirección 123');

-- CITY
EXECUTE PKG_CITY.ADD_CITY('Nueva ciudad', 'Cundinamarca');
--SELECT PKG_CITY.READ_CITY FROM DUAL;
EXECUTE PKG_CITY.UPDATE_CITY(33, 'Nuevo ciudad editada','Nariño');


-- MEDICATION INVENTORY
EXECUTE PKG_MEDICATION_INVENTORY.ADD_MEDICATION_INVENTORY(1);
EXECUTE PKG_MEDICATION_INVENTORY.ADD_MEDICATION_INVENTORY(1000);
--SELECT PKG_MEDICATION_INVENTORY.READ_MEDICATION_INVENTORY FROM DUAL;
EXECUTE PKG_MEDICATION_INVENTORY.UPDATE_MEDICATION_INVENTORY(12, 13);

-- HOSPITAL
EXECUTE PKG_HOSPITAL.ADD_HOSPITAL('Nuevo hospital', 10, 10, 'Batallón 2', 'Yopal', 'Dirección 345');
--SELECT PKG_HOSPITAL.READ_HOSPITAL FROM DUAL;
EXECUTE PKG_HOSPITAL.UPDATE_HOSPITAL('Nuevo hospital', 111, 111, 'Batallón 2', 'Dirección 147');

-- PERSON
EXECUTE PKG_PERSON.ADD_PERSON('CC', '1235478965', 'PRUEBA', 'UNITARIA', 'M', TO_DATE('01/26/1979', 'MM/DD/YYYY'), 'laprueba@mail.com');
--SELECT PKG_PERSON.READ_PERSON FROM DUAL;
EXECUTE PKG_PERSON.UPDATE_PERSON('CC', '1235478965', 'A', 'lapruebaeditada@mail.com');

-- PATIENT
EXECUTE PKG_PERSON.ADD_PATIENT('CC', '3625987458', 'PACIENTE', 'DE PRUEBA', 'M', TO_DATE('06/12/1990', 'MM/DD/YYYY'), 'paciente1@mail.com');
--SELECT PKG_PERSON.READ_PATIENTS FROM DUAL;
--SELECT PKG_PERSON.READ_SPECIFIC_PATIENT('CC', '3625987458') FROM DUAL;
--SELECT PKG_PERSON.READ_PATIENT_BACK_PROC('CC', '3625987458') FROM DUAL;
--SELECT PKG_PERSON.READ_PATIENT_BACK_DIS('CC', '3625987458') FROM DUAL;

--SELECT PKG_PATIENT.READ_PATIENT('CC', '3625987458') FROM DUAL;
--SELECT PKG_PATIENT.READ_BACK_PROC('CC', '3625987458') FROM DUAL;
--SELECT PKG_PATIENT.READ_BACK_DIS('CC', '3625987458') FROM DUAL;
EXECUTE PKG_PERSON.UPDATE_PATIENT('CC', '3625987458', 'I');

-- DOCTOR
EXECUTE PKG_PERSON.ADD_DOCTOR('CC', '1236547859', 'DOCTOR', 'DE PRUEBA', 'M', TO_DATE('06/26/1980', 'MM/DD/YYYY'), 'doctor1@mail.com', 'Armada', 'Dermatologia');
--SELECT PKG_PERSON.READ_DOCTOR FROM DUAL;

--SELECT PKG_DOCTOR.READ_DOCTOR FROM DUAL;
--SELECT PKG_DOCTOR.READ_SPECIFIC_DOCTOR('doctor1@mail.com') FROM DUAL;
--SELECT PKG_DOCTOR.READ_APPOINTMENTS('doctor1@mail.com') FROM DUAL;
EXECUTE PKG_PERSON.UPDATE_DOCTOR('CC', '1236547859', 'I', 'Ejercito', 'Neurocirugia');

-- NURSE
EXECUTE PKG_PERSON.ADD_NURSE('CC', '1458758965', 'ENFERMERO', 'DE PRUEBA', 'M', TO_DATE('06/26/1980', 'MM/DD/YYYY'), 'enfermero1@mail.com', 'Armada', 'Dermatologia');
--SELECT PKG_PERSON.READ_NURSE FROM DUAL;
--SELECT PKG_NURSE.READ_NURSE FROM DUAL;
--SELECT PKG_NURSE.READ_SPECIFIC_NURSE('enfermero1@mail.com') FROM DUAL;
--SELECT PKG_NURSE.READ_APPOINTMENTS('enfermero1@mail.com') FROM DUAL;
EXECUTE PKG_PERSON.UPDATE_NURSE('CC', '1458758965', 'I', 'Ejercito', 'Neurocirugia');



-- CLINICAL HISTORY
EXECUTE PKG_CLINICAL_HISTORY.ADD_CLINICAL_HISTORY('CC', '3625987458');
--SELECT PKG_CLINICAL_HISTORY.READ_CLINICAL_HISTORY('CC', '3625987458') FROM DUAL;

-- BACKGROUND DISEASE
EXECUTE PKG_CLINICAL_HISTORY.ADD_BACKGROUND_DISEASE('CC', '3625987458', 'Dolor Crónico', 'Un dolor muy fuerte');
EXECUTE PKG_CLINICAL_HISTORY.ADD_BACKGROUND_DISEASE('CC', '3625987458', 'Dolor no tan crónico', 'Un dolor no muy fuerte');
--SELECT PKG_CLINICAL_HISTORY.READ_BACKGROUND_DISEASE('CC', '3625987458') FROM DUAL;


-- BACKGROUND PROCEDURE
EXECUTE PKG_CLINICAL_HISTORY.ADD_BACKGROUND_PROCEDURE('CC', '3625987458', 'Cirugía de rodilla', TO_DATE('06/12/2015 10:00', 'MM/DD/YYYY hh24:mi'), 'Poco ejercicio y mucho reposo', 'Nuevo hospital', 'Paracetamol', 'Cápsulas de 50mg', 'Bayer', 'Oral');
--SELECT PKG_CLINICAL_HISTORY.READ_BACKGROUND_PROCEDURE('CC', '3625987458') FROM DUAL;

-- APPOINTMENT
EXECUTE PKG_CLINICAL_HISTORY.ADD_APPOINTMENT('CC', '3625987458', 'Dolor de codo', TO_DATE('06/12/2022 14:30', 'MM/DD/YYYY hh24:mi'), 'doctor1@mail.com', 'Nuevo hospital');
--SELECT PKG_CLINICAL_HISTORY.READ_APPOINTMENTS FROM DUAL;
--SELECT PKG_CLINICAL_HISTORY.READ_BACKGROUND_PROCEDURE('CC', '3625987458') FROM DUAL;
EXECUTE PKG_CLINICAL_HISTORY.ADD_APPOINTMENT_NURSE('enfermero1@mail.com', 1);

EXECUTE PKG_APPOINTMENT.ADD_APPOINTMENT('CC', '3625987458', 'Dolor del otro codo', TO_DATE('06/06/2022 08:30', 'MM/DD/YYYY hh24:mi'), 'doctor1@mail.com', 'Nuevo hospital');

EXECUTE PKG_APPOINTMENT.ADD_APPOINTMENT_NURSE('enfermero1@mail.com', 10);
--SELECT PKG_APPOINTMENT.READ_APPOINTMENTS FROM DUAL;
--SELECT PKG_APPOINTMENT.READ_DOC_APPOINTMENTS('doctor1@mail.com') FROM DUAL;
--SELECT PKG_APPOINTMENT.READ_NUR_APPOINTMENTS('enfermero1@mail.com') FROM DUAL;
--SELECT PKG_APPOINTMENT.READ_PAT_APPOINTMENTS('paciente1@mail.com') FROM DUAL;

-- PROCEDURES
EXECUTE PKG_PROCEDURES.ADD_PROCEDURE('CC', '3625987458', 'PROCEDIMIENTO DE PRUEBA', TO_DATE('06/09/2022 19:30', 'MM/DD/YYYY hh24:mi'), 'Nuevo hospital', 'doctor1@mail.com');