-- SUPPLY
EXECUTE PKG_SUPPLY.ADD_SUPPLY('TEST', 1, 1);
EXECUTE PKG_SUPPLY.ADD_SUPPLY('TEST2', 1000, 10);
SELECT PKG_SUPPLY.READ_SUPPLY FROM DUAL;
EXECUTE PKG_SUPPLY.UPDATE_SUPPLY(16, 'TEST UPDATED', 11, 10);

-- SUPPLIES INVENTORY
EXECUTE PKG_SUPPLIES_INVENTORY.ADD_SUPPLIES_INVENTORY(1);
EXECUTE PKG_SUPPLIES_INVENTORY.ADD_SUPPLIES_INVENTORY(1000);
SELECT PKG_SUPPLIES_INVENTORY.READ_SUPPLIES_INVENTORY FROM DUAL;
EXECUTE PKG_SUPPLIES_INVENTORY.UPDATE_SUPPLIES_INVENTORY(2, 13);

-- MILITARY UNIT
EXECUTE PKG_MILITARY_UNIT.ADD_MILITARY_UNIT('UNIDAD DE PRUEBA', NULL, NULL);
SELECT PKG_MILITARY_UNIT.READ_MILITARY_UNIT FROM DUAL;