/*
COMO doctor
QUIERO registrarme en el sistema PARA PODER empezar a agendar, revisar y atender
citas de los pacientes de la DISAN.
*/

-- REGISTRAR PERSONA EN EL SISTEMA
    -- CHECK: Tipo de documento
    -- CHECK: Género
    -- CHECK: Email
        -- NO puede tener caracteres especiales
EXECUTE PKG_PERSON.ADD_PERSON('CC', 1458759875, 'Manuel Elkin', 'Patarroyo', 'M', TO_DATE('05/15/1969', 'MM/DD/YYYY'),'manuel@mail.com'); 
--SELECT PKG_PERSON.READ_PERSON FROM DUAL;

-- REGISTRAR ESPECIALIDAD EN EL SISTEMA
EXECUTE PKG_SPECIALTY.ADD_SPECIALTY('Nueva especialidad');
--SELECT PKG_SPECIALTY.READ_SPECIALTIES FROM DUAL;

-- REGISTRAR EL DOCTOR EN EL SISTEMA
    -- CHECK: Fuerza militar
EXECUTE PKG_DOCTOR.ADD_DOCTOR('CC', 1458759875, 'Armada', 11);
--SELECT PKG_PERSON.READ_DOCTOR FROM DUAL;

-- REVISAR CITAS PENDIENTES
SELECT PKG_DOCTOR.READ_APPOINTMENTS('CC', 1458759875) FROM DUAL;

-- AGREGAR ENFERMERO A LA CITA
SELECT PKG_NURSE.READ_NURSE FROM DUAL;
EXECUTE PKG_APPOINTMENT.ADD_APPOINTMENT_NURSE('CC', 4252609306, 2);
--SELECT PKG_NURSE.READ_APPOINTMENTS('CC', 4252609306) FROM DUAL;

-- AÑADIR DIAGNÓSTICO
EXECUTE PKG_APPOINTMENT.ADD_DIAGNOSIS(2, 'El médico añadió un diagnóstico');

-- CREAR PLAN DE MANEJO
EXECUTE PKG_MANAGEMENT_PLAN.ADD_MANAGEMENT_PLAN('El médico asignó un plan de manejo');
--SELECT PKG_MANAGEMENT_PLAN.READ_MANAGEMENT_PLAN FROM DUAL;

-- ASIGNAR PLAN DE MANEJO A LA CITA
EXECUTE PKG_APPOINTMENT.ADD_MANAGEMENT_PLAN(11, 2);

-- FINALIZAR CITA
EXECUTE PKG_APPOINTMENT.FINISH_APPOINTMENT(2);

-- REVISAR PROCEDIMIENTOS PENDIENTES
SELECT PKG_PROCEDURE.READ_DOCTOR_PROCEDURES('CC', 1458759875) FROM DUAL;

-- AGREGAR ENFERMERO AL PROCEDIMIENTO
EXECUTE PKG_PROCEDURE.ADD_PROCEDURE_NURSE('CC', 4252609306, 11);
--SELECT PKG_PROCEDURE.READ_NURSE_PROCEDURES('CC', 4252609306) FROM DUAL;

-- CREAR PLAN DE MANEJO
EXECUTE PKG_MANAGEMENT_PLAN.ADD_MANAGEMENT_PLAN('El médico asignó un plan de manejo al procedimiento');
--SELECT PKG_MANAGEMENT_PLAN.READ_MANAGEMENT_PLAN FROM DUAL;

-- ASIGNAR PLAN DE MANEJO AL PROCEDIMIENTO
EXECUTE PKG_PROCEDURE.ADD_MANAGEMENT_PLAN(11, 12);

-- FINALIZAR PROCEDIMIENTO
EXECUTE PKG_PROCEDURE.FINISH_PROCEDURE(11);



