/*
COMO paciente
QUIERO registrarme en el sistema, ver los médicos que me pueden atender
de acuerdo a una especialidad dada PARA PODER agendar una cita y un procedimiento 
que me gustaría realizar.
*/

-- REGISTRAR PERSONA EN EL SISTEMA
    -- CHECK: Tipo de documento
    -- CHECK: Género
    -- CHECK: Email
        -- NO puede tener caracteres especiales
EXECUTE PKG_PERSON.ADD_PERSON('CC', 1026306655, 'Juan David', 'Murillo', 'M', TO_DATE('09/20/1999', 'MM/DD/YYYY'),'juan@mail.com'); 
--SELECT PKG_PERSON.READ_PERSON FROM DUAL;

-- REGISTRAR PACIENTE EN EL SISTEMA
EXECUTE PKG_PERSON.ADD_PATIENT('CC', 1026306655);
--SELECT PKG_PERSON.READ_PATIENTS FROM DUAL;

-- INICIALIZAR HISTORIA CLÍNICA
EXECUTE PKG_CLINICAL_HISTORY.ADD_CLINICAL_HISTORY('CC', 1026306655);

-- VER LISTADO DE ESPECIALIDADES
SELECT PKG_SPECIALTY.READ_SPECIALTIES FROM DUAL;

-- VER MÉDICOS POR ESPECIALIDAD
SELECT PKG_DOCTOR.READ_DOC_SPECIALTY(11) FROM DUAL;

-- VER MÉDICO EN ESPECÍFICO
SELECT PKG_DOCTOR.READ_SPECIFIC_DOCTOR('CC', 1458759875) FROM DUAL;

-- CONSULTAR HISTORIA CLÍNICA
SELECT PKG_CLINICAL_HISTORY.READ_CLINICAL_HISTORY('CC', 1026306655) FROM DUAL;

-- CONSULTAR HOSPITAL
SELECT PKG_HOSPITAL.READ_HOSPITAL FROM DUAL;

-- AGENDAR CITA
EXECUTE PKG_APPOINTMENT.ADD_APPOINTMENT(5, 'Dolor de espalda', TO_TIMESTAMP('07/09/2021 14:00', 'MM/DD/YYYY hh24:mi'), 1);
--SELECT PKG_APPOINTMENT.READ_APPOINTMENTS FROM DUAL;

-- AGREGAR DOCTOR A LA CITA
EXECUTE PKG_APPOINTMENT.ADD_APPOINTMENT_DOCTOR('CC', 1458759875, 2);
--SELECT PKG_DOCTOR.READ_APPOINTMENTS('CC', 1458759875) FROM DUAL;

-- AGENDAR PROCEDIMIENTO
EXECUTE PKG_PROCEDURE.ADD_PROCEDURE(TO_TIMESTAMP('07/11/2021 14:00', 'MM/DD/YYYY hh24:mi'), 'Procedimiento para el dolor de espalda', 'Este es un procedimiento para el dolor de espalda', 5, 1);
--SELECT PKG_PROCEDURE.READ_PROCEDURES FROM DUAL;

-- AGREGAR DOCTOR AL PROCEDIMIENTO
EXECUTE PKG_PROCEDURE.ADD_PROCEDURE_DOCTOR('CC', 1458759875, 11);
--SELECT PKG_PROCEDURE.READ_DOCTOR_PROCEDURES('CC', 1458759875) FROM DUAL;

/*
    EL DOCTOR ATIENDE Y FINALIZA LA CITA
*/

-- REVISAR HISTORIA CLÍNICA
SELECT PKG_CLINICAL_HISTORY.READ_CLINICAL_HISTORY('CC', 1026306655) FROM DUAL;

-- REVISAR ANTECEDENTES
SELECT PKG_BACKGROUND.READ_PATIENT_BACKGROUNDS(5) FROM DUAL;