/*
COMO doctor QUIERO revisar los medicamentos registrados en el sistema
y sus existencias PARA PODER recetarlos a mis pacientes luego de una cita o 
un procedimiento.
*/
-- BUSCAR TODOS LOS MEDICAMENTOS
SELECT PA_DOCTOR.READ_ALL_MEDICINES FROM DUAL;

-- BUSCAR MEDICAMENTO POR NOMBRE
SELECT PA_DOCTOR.READ_SPEC_MED('BENZOYL PEROXIDE') FROM DUAL;

-- ASIGNAR MEDICAMENTO A CITA
    -- TRAER EL PLAN DE MANEJO DE LA CITA
    -- ASIGNAR EL MEDICAMENTO A ESE PLAN DE MANEJO
    -- RESTAR EN 1 LA CANTIDAD DE UNIDADES DISPONIBLES
EXECUTE PA_DOCTOR.ADD_MED_TO_APPOINTMENT('BENZOYL PEROXIDE', 1);

-- ASIGNAR MEDICAMENTO A PROCEDIMIENTO
    -- TRAER EL PLAN DE MANEJO DEL PROCEDIMIENTO
    -- ASIGNAR EL MEDICAMENTO A ESE PLAN DE MANEJO
    -- RESTAR EN 1 LA CANTIDAD DE UNIDADES DISPONIBLES
EXECUTE PA_DOCTOR.ADD_MED_TO_PROCEDURE('BENZOYL PEROXIDE', 1);

