/*
COMO doctor QUIERO revisar los medicamentos registrados en el sistema
y sus existencias PARA PODER recetarlos a mis pacientes luego de una cita o 
un procedimiento.
*/
-- BUSCAR TODOS LOS MEDICAMENTOS
SELECT PKG_MEDICINES.READ_ALL_MED FROM DUAL;

-- BUSCAR MEDICAMENTO POR NOMBRE
SELECT PKG_MEDICINES.READ_SPEC_MED('MEDICAMENTO 2') FROM DUAL;

-- ASIGNAR MEDICAMENTO A CITA
    -- TRAER EL PLAN DE MANEJO DE LA CITA
    -- ASIGNAR EL MEDICAMENTO A ESE PLAN DE MANEJO
    -- RESTAR EN 1 LA CANTIDAD DE UNIDADES DISPONIBLES
EXECUTE PKG_MEDICINES.ADD_MED_TO_APPOINTMENT('MEDICAMENTO 2', 2);

-- ASIGNAR MEDICAMENTO A PROCEDIMIENTO
    -- TRAER EL PLAN DE MANEJO DEL PROCEDIMIENTO
    -- ASIGNAR EL MEDICAMENTO A ESE PLAN DE MANEJO
    -- RESTAR EN 1 LA CANTIDAD DE UNIDADES DISPONIBLES
EXECUTE PKG_MEDICINES.ADD_MED_TO_PROCEDURE('MEDICAMENTO 3', 10);